# Generated by Django 5.1.7 on 2025-04-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Unique Identifier (IDS)", max_length=30
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Regulation Title", max_length=510),
                ),
                ("date", models.DateField(help_text="Approval Date")),
                (
                    "authority",
                    models.CharField(help_text="Approval Authority", max_length=255),
                ),
                ("link", models.URLField(blank=True, help_text="Regulation Link")),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", help_text="Regulation Text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulation",
                "verbose_name_plural": "Regulations",
                "ordering": ["-date", "title"],
            },
        ),
    ]
