# Generated by Django 5.1.7 on 2025-05-18 02:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="date",
            field=django_jalali.db.models.jDateField(help_text="Approval Date"),
        ),
    ]
