# Generated by Django 5.1.7 on 2025-03-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Regulation Title", max_length=255),
                ),
                ("description", models.TextField(blank=True, help_text="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Regulation",
                "verbose_name_plural": "Regulations",
                "ordering": ["-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Article Title", max_length=50)),
                (
                    "text",
                    models.TextField(blank=True, default="", help_text="Article Text"),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        help_text="Related Regulation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="regulation.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["regulation", "title"],
                "unique_together": {("regulation", "title")},
            },
        ),
        migrations.CreateModel(
            name="Clause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Clause Title", max_length=50)),
                ("text", models.TextField(help_text="Clause Text")),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Related Article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="regulation.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clause",
                "verbose_name_plural": "Clauses",
                "ordering": ["article", "title"],
                "unique_together": {("article", "title")},
            },
        ),
    ]
