# Generated by Django 5.1.7 on 2025-03-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Regulation Title", max_length=255),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Regulation Number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(blank=True, help_text="Approval Date", null=True),
                ),
                (
                    "implementation_date",
                    models.DateField(
                        blank=True, help_text="Implementation Date", null=True
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Description")),
                ("is_active", models.BooleanField(default=True, help_text="Is Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True,
                        help_text="References to other regulations",
                        related_name="referenced_by",
                        to="regulation.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulation",
                "verbose_name_plural": "Regulations",
                "ordering": ["-approval_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(help_text="Article Number", max_length=50)),
                ("text", models.TextField(help_text="Article Text")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display Order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True,
                        help_text="References to other articles",
                        related_name="referenced_by",
                        to="regulation.article",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        help_text="Related Regulation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="regulation.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["regulation", "order", "number"],
                "unique_together": {("regulation", "number")},
            },
        ),
        migrations.CreateModel(
            name="Clause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(help_text="Clause Number", max_length=50)),
                ("text", models.TextField(help_text="Clause Text")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display Order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Related Article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="regulation.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clause",
                "verbose_name_plural": "Clauses",
                "ordering": ["article", "order", "number"],
                "unique_together": {("article", "number")},
            },
        ),
        migrations.CreateModel(
            name="RegulationReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.TextField(blank=True, help_text="Reference Context"),
                ),
                (
                    "reference_text",
                    models.CharField(
                        blank=True,
                        help_text="Reference Text (e.g., According to Article 10 of...)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_regulation",
                    models.ForeignKey(
                        help_text="Source Regulation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_references",
                        to="regulation.regulation",
                    ),
                ),
                (
                    "target_regulation",
                    models.ForeignKey(
                        help_text="Target Regulation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_references",
                        to="regulation.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulation Reference",
                "verbose_name_plural": "Regulation References",
                "unique_together": {
                    ("source_regulation", "target_regulation", "reference_text")
                },
            },
        ),
    ]
