# Generated by Django 5.1.7 on 2025-03-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regulation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["regulation", "number"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="clause",
            options={
                "ordering": ["article", "number"],
                "verbose_name": "Clause",
                "verbose_name_plural": "Clauses",
            },
        ),
        migrations.AlterModelOptions(
            name="regulation",
            options={
                "ordering": ["-created_at", "title"],
                "verbose_name": "Regulation",
                "verbose_name_plural": "Regulations",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="order",
        ),
        migrations.RemoveField(
            model_name="article",
            name="references",
        ),
        migrations.RemoveField(
            model_name="article",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="clause",
            name="order",
        ),
        migrations.RemoveField(
            model_name="clause",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="implementation_date",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="number",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="references",
        ),
        migrations.RemoveField(
            model_name="regulation",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="RegulationReference",
        ),
    ]
