# Generated by Django 5.1.7 on 2025-03-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regulation", "0002_alter_article_options_alter_clause_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clause",
            name="created_at",
        ),
    ]
