version: "3"
services:
  db-postgres:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=compliance_ai_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  db-neo4j:
    image: neo4j:latest
    volumes:
        - neo4j_data:/data
    environment:
        - NEO4J_AUTH=neo4j/lightrag
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

  db-mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: lightrag
    ports:
      - "27017:27017"
    restart: always

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - db-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: lightrag
      ME_CONFIG_MONGODB_URL: mongodb://mongo:lightrag@db-mongo:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    restart: always

  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db-postgres
  #     - db-neo4j
  #     - db-mongo
  #   volumes:
  #     - static:/code/static
  #     - media:/code/media
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=compliance_ai_assistant.settings.production
  #     - ALLOWED_HOSTS=*
  #     - DATABASE_NAME=compliance_ai_assistant
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_HOST=db-postgres
  #     - DATABASE_PORT=5432
  #   ports:
  #     - "8000:8000"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   restart: unless-stopped

volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../databases/db-postgres
  neo4j_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../databases/db-neo4j
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../databases/db-mongo
  static:
    driver: local
  media:
    driver: local